// =============================================
// GLOBETREK — DATA FILE
// All static data for destinations, guides, etc.
// =============================================

const DESTINATIONS = [
  // ===== ORIGINAL 8 =====
  {
    id: 1,
    name: "Bali, Indonesia",
    country: "Indonesia",
    region: "Asia",
    category: "Beach",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&q=80",
    description: "Bali is a living postcard, an Indonesian paradise that feels like a fantasy. Breathtaking rice terraces, ornate temples, and volcanic mountains meet a sublime coastline. A destination unlike any other.",
    attractions: ["Ubud Monkey Forest", "Tegallalang Rice Terraces", "Tanah Lot Temple", "Kuta Beach", "Mount Agung"],
    bestTime: "April to October (dry season)",
    food: ["Nasi Goreng", "Babi Guling", "Satay", "Gado-Gado", "Bubur Injin"],
    tips: ["Rent a scooter for local transport", "Respect temple dress codes", "Bargain at local markets", "Try a cooking class"],
    budget: { accommodation: 60, food: 25, transport: 20, activities: 30 },
    weather: "Bali",
    trending: true,
  },
  {
    id: 2,
    name: "Switzerland",
    country: "Switzerland",
    region: "Europe",
    category: "Mountains",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1200&q=80",
    description: "Switzerland is a storybook destination of snow-capped peaks, crystal-clear lakes, and chocolate-box villages. From skiing in the Alps to sailing on Lake Geneva, every view is a masterpiece.",
    attractions: ["Matterhorn", "Lake Geneva", "Jungfraujoch", "Zermatt", "Rhine Falls"],
    bestTime: "June to September (summer) / December to March (skiing)",
    food: ["Fondue", "Raclette", "Rösti", "Zürcher Geschnetzeltes", "Swiss chocolate"],
    tips: ["Book trains in advance", "Swiss Rail Pass is worth it", "Carry cash for small shops", "Pack layers even in summer"],
    budget: { accommodation: 180, food: 70, transport: 60, activities: 80 },
    weather: "Zurich",
    trending: true,
  },
  {
    id: 3,
    name: "Maldives",
    country: "Maldives",
    region: "Asia",
    category: "Beach",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1200&q=80",
    description: "The Maldives is the ultimate tropical paradise — an archipelago of 1,200 islands with crystal lagoons, vibrant coral reefs, and iconic overwater bungalows. Pure luxury meets natural wonder.",
    attractions: ["Overwater Villas", "Snorkeling & Diving", "Male Fish Market", "Whale Shark Watching", "Biyadhoo Island"],
    bestTime: "November to April (dry season)",
    food: ["Mas Huni", "Garudiya", "Bis Keemiya", "Fihunu Mas", "Saagu Bondi"],
    tips: ["Book overwater villas early", "Bring reef-safe sunscreen", "Seaplanes are the main transport", "Budget for activities separately"],
    budget: { accommodation: 400, food: 80, transport: 120, activities: 100 },
    weather: "Male",
    trending: true,
  },
  {
    id: 4,
    name: "Paris, France",
    country: "France",
    region: "Europe",
    category: "City",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&q=80",
    description: "Paris, the City of Light, enchants visitors with the Eiffel Tower's sparkle, world-class museums, and the incomparable Parisian café culture. Romance and history meet on every cobblestone street.",
    attractions: ["Eiffel Tower", "Louvre Museum", "Notre-Dame Cathedral", "Montmartre", "Palace of Versailles"],
    bestTime: "April to June, September to October",
    food: ["Croissants", "Crêpes", "Steak Frites", "French Onion Soup", "Macarons"],
    tips: ["Buy a Paris Visite metro pass", "Book museums online to skip queues", "Tipping is optional", "Most museums are free on the first Sunday"],
    budget: { accommodation: 130, food: 55, transport: 30, activities: 50 },
    weather: "Paris",
    trending: true,
  },
  {
    id: 5,
    name: "Tokyo, Japan",
    country: "Japan",
    region: "Asia",
    category: "City",
    rating: 4.9,
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=1200&q=80",
    description: "Tokyo is a magnificent contradiction — ancient temples stand beside neon-lit skyscrapers, serene shrines neighbor bustling tech districts. The world's most populous city is also its most orderly and fascinating.",
    attractions: ["Shibuya Crossing", "Senso-ji Temple", "TeamLab Planets", "Shinjuku", "Akihabara"],
    bestTime: "March to May (cherry blossoms) / September to November",
    food: ["Sushi", "Ramen", "Yakitori", "Tempura", "Wagyu Beef"],
    tips: ["Get a Suica card for transit", "7-Eleven food is surprisingly great", "Bow when greeting locals", "Learn a few Japanese phrases"],
    budget: { accommodation: 100, food: 40, transport: 25, activities: 45 },
    weather: "Tokyo",
    trending: false,
  },
  {
    id: 6,
    name: "Santorini, Greece",
    country: "Greece",
    region: "Europe",
    category: "Beach",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1200&q=80",
    description: "Santorini is a crescent of drama — volcanic cliffs, whitewashed buildings with blue domes, and sunsets that stop time. The most photographed island in the world absolutely lives up to every expectation.",
    attractions: ["Oia Sunset", "Fira Town", "Red Beach", "Akrotiri Archaeological Site", "Amoudi Bay"],
    bestTime: "April to November",
    food: ["Fava", "Tomatokeftedes", "Grilled Octopus", "Moussaka", "Baklava"],
    tips: ["Stay in Oia for the best sunset", "Book accommodations 6 months ahead", "Donkeys or cable car from the port", "Try local Assyrtiko wine"],
    budget: { accommodation: 200, food: 60, transport: 30, activities: 50 },
    weather: "Santorini",
    trending: false,
  },
  {
    id: 7,
    name: "New York, USA",
    country: "USA",
    region: "Americas",
    category: "City",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=1200&q=80",
    description: "New York City — the city that never sleeps and never disappoints. From the neon blaze of Times Square to the serene paths of Central Park, NYC is every traveler's dream distilled into five boroughs.",
    attractions: ["Statue of Liberty", "Central Park", "Times Square", "Brooklyn Bridge", "The Metropolitan Museum of Art"],
    bestTime: "April to June, September to November",
    food: ["NY Pizza", "Bagels", "Cheesecake", "Hot Dogs", "Pastrami Sandwich"],
    tips: ["Use the subway — it goes everywhere", "Book popular restaurants weeks ahead", "Free Staten Island Ferry views are stunning", "NYCGO card for museum discounts"],
    budget: { accommodation: 200, food: 70, transport: 30, activities: 60 },
    weather: "New York",
    trending: false,
  },
  {
    id: 8,
    name: "Dubai, UAE",
    country: "UAE",
    region: "Asia",
    category: "City",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&q=80",
    description: "Dubai is audacious ambition made real. The world's tallest building, indoor skiing in the desert, islands built in the shape of a palm — Dubai doesn't just push limits, it ignores they exist.",
    attractions: ["Burj Khalifa", "The Palm Jumeirah", "Dubai Mall", "Desert Safari", "Dubai Frame"],
    bestTime: "November to March (cool season)",
    food: ["Al Harees", "Shawarma", "Machboos", "Luqaimat", "Camel Milk"],
    tips: ["Dress modestly in public", "Ramadan has special rules for visitors", "Taxis are metered and reliable", "Dubai Metro is excellent"],
    budget: { accommodation: 150, food: 50, transport: 30, activities: 80 },
    weather: "Dubai",
    trending: false,
  },

  // ===== INDIAN DESTINATIONS =====
  {
    id: 9,
    name: "Hyderabad, India",
    country: "India",
    region: "Asia",
    category: "City",
    rating: 4.5,
    image: "https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=1200&q=80",
    description: "Hyderabad, the City of Pearls, is a dazzling blend of Mughal grandeur and modern technology. Home to the iconic Charminar, the world-famous Hyderabadi biryani, and India's booming IT corridor — HITEC City.",
    attractions: ["Charminar", "Golconda Fort", "Hussain Sagar Lake", "Ramoji Film City", "Salar Jung Museum"],
    bestTime: "October to February (winter)",
    food: ["Hyderabadi Biryani", "Haleem", "Mirchi ka Salan", "Qubani ka Meetha", "Irani Chai"],
    tips: ["Try biryani at Paradise or Bawarchi", "Use Ola/Uber for local transport", "Visit Charminar early morning to avoid crowds", "Bargain at Laad Bazaar for bangles"],
    budget: { accommodation: 30, food: 10, transport: 8, activities: 15 },
    weather: "Hyderabad",
    trending: true,
  },
  {
    id: 10,
    name: "Kerala, India",
    country: "India",
    region: "Asia",
    category: "Nature",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200&q=80",
    description: "Kerala — God's Own Country — is a paradise of emerald backwaters, lush hill stations, pristine beaches, and ancient Ayurvedic traditions. A serene escape where nature reigns supreme.",
    attractions: ["Alleppey Backwaters", "Munnar Tea Gardens", "Kovalam Beach", "Periyar Wildlife Sanctuary", "Varkala Cliff"],
    bestTime: "September to March (post-monsoon)",
    food: ["Kerala Fish Curry", "Appam with Stew", "Puttu and Kadala", "Kerala Prawn Curry", "Payasam"],
    tips: ["Book a houseboat stay in Alleppey", "Try Ayurvedic spa treatments", "Carry mosquito repellent", "Respect local customs at temples"],
    budget: { accommodation: 35, food: 12, transport: 10, activities: 20 },
    weather: "Kochi",
    trending: true,
  },
  {
    id: 11,
    name: "Goa, India",
    country: "India",
    region: "Asia",
    category: "Beach",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=1200&q=80",
    description: "Goa is India's beach paradise — where golden sands meet Portuguese heritage, vibrant nightlife, and a laid-back coastal vibe. From tranquil North Goa to the party scene of South Goa, there's something for everyone.",
    attractions: ["Baga Beach", "Dudhsagar Waterfalls", "Basilica of Bom Jesus", "Anjuna Flea Market", "Fort Aguada"],
    bestTime: "November to February (dry season)",
    food: ["Goan Fish Curry", "Prawn Balchao", "Bebinca", "Vindaloo", "Feni Cocktails"],
    tips: ["Rent a scooter to explore", "Visit North Goa for heritage, South for beaches", "Avoid monsoon season (June-September)", "Book beach shacks early in season"],
    budget: { accommodation: 40, food: 15, transport: 10, activities: 20 },
    weather: "Goa",
    trending: true,
  },
  {
    id: 12,
    name: "Manali, India",
    country: "India",
    region: "Asia",
    category: "Mountains",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=1200&q=80",
    description: "Manali is the crown jewel of the Indian Himalayas — a breathtaking mountain town where snow-capped peaks, roaring rivers, and ancient monasteries create an unforgettable adventure destination.",
    attractions: ["Rohtang Pass", "Solang Valley", "Hadimba Temple", "Old Manali", "Beas River Rafting"],
    bestTime: "October to June (avoid monsoon July-September)",
    food: ["Sidu", "Dham", "Trout Fish", "Chha Gosht", "Babru"],
    tips: ["Carry warm clothes even in summer", "Acclimatize before going to high altitude", "Book permits for Rohtang Pass in advance", "Try adventure sports at Solang Valley"],
    budget: { accommodation: 25, food: 10, transport: 15, activities: 25 },
    weather: "Manali",
    trending: false,
  },
  {
    id: 13,
    name: "Rajasthan, India",
    country: "India",
    region: "Asia",
    category: "Culture",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1477587458883-47145ed94b23?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1477587458883-47145ed94b23?w=1200&q=80",
    description: "Rajasthan is the land of maharajas, majestic forts, golden deserts, and vibrant culture. From the pink city of Jaipur to the blue city of Jodhpur, every corner tells a story of royal grandeur.",
    attractions: ["Amber Fort Jaipur", "Mehrangarh Fort", "Jaisalmer Desert Safari", "Lake Pichola Udaipur", "Hawa Mahal"],
    bestTime: "October to March (winter)",
    food: ["Dal Baati Churma", "Laal Maas", "Gatte ki Sabzi", "Ker Sangri", "Ghevar"],
    tips: ["Hire a local guide at forts", "Bargain at local bazaars", "Try camel safari in Jaisalmer", "Book heritage hotels for unique experience"],
    budget: { accommodation: 35, food: 12, transport: 15, activities: 20 },
    weather: "Jaipur",
    trending: false,
  },
  {
    id: 14,
    name: "Agra, India",
    country: "India",
    region: "Asia",
    category: "Culture",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=1200&q=80",
    description: "Agra is home to one of the world's greatest wonders — the Taj Mahal. This Mughal city on the banks of the Yamuna River is a testament to eternal love, architectural brilliance, and India's rich imperial history.",
    attractions: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri", "Mehtab Bagh", "Itimad-ud-Daula"],
    bestTime: "October to March (winter)",
    food: ["Petha", "Dalmoth", "Bedai Puri", "Mughlai Biryani", "Jalebi"],
    tips: ["Visit Taj Mahal at sunrise", "Buy tickets online to skip queues", "Hire official guides only", "Carry water and wear comfortable shoes"],
    budget: { accommodation: 30, food: 10, transport: 10, activities: 15 },
    weather: "Agra",
    trending: false,
  },

  // ===== MORE INTERNATIONAL =====
  {
    id: 15,
    name: "London, UK",
    country: "United Kingdom",
    region: "Europe",
    category: "City",
    rating: 4.7,
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1200&q=80",
    description: "London is a world in one city — where centuries of history meet cutting-edge culture. From Buckingham Palace to the Tate Modern, from black cabs to the Tube, London never stops surprising and inspiring.",
    attractions: ["Big Ben & Westminster", "Tower of London", "Buckingham Palace", "British Museum", "London Eye"],
    bestTime: "June to August (summer)",
    food: ["Fish and Chips", "Full English Breakfast", "Chicken Tikka Masala", "Afternoon Tea", "Pie and Mash"],
    tips: ["Get an Oyster card for the Tube", "Many museums are free", "Book popular attractions in advance", "Weather changes quickly — carry an umbrella"],
    budget: { accommodation: 150, food: 60, transport: 35, activities: 55 },
    weather: "London",
    trending: false,
  },
  {
    id: 16,
    name: "Singapore",
    country: "Singapore",
    region: "Asia",
    category: "City",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200&q=80",
    description: "Singapore is a futuristic city-state where gleaming skyscrapers meet lush tropical greenery, and diverse cultures — Chinese, Malay, Indian — blend seamlessly. Clean, efficient, and endlessly fascinating.",
    attractions: ["Marina Bay Sands", "Gardens by the Bay", "Sentosa Island", "Chinatown", "Universal Studios"],
    bestTime: "February to April (dry season)",
    food: ["Hainanese Chicken Rice", "Laksa", "Chilli Crab", "Char Kway Teow", "Kaya Toast"],
    tips: ["MRT is excellent — use it", "Hawker centres for cheap amazing food", "Grab app for taxis", "Singapore is very safe"],
    budget: { accommodation: 120, food: 35, transport: 20, activities: 60 },
    weather: "Singapore",
    trending: false,
  },
  {
    id: 17,
    name: "Bangkok, Thailand",
    country: "Thailand",
    region: "Asia",
    category: "City",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1200&q=80",
    description: "Bangkok is a sensory explosion — magnificent temples gilded in gold, chaotic street markets, aromatic street food, and electrifying nightlife all coexist in Thailand's magnificent capital city.",
    attractions: ["Grand Palace", "Wat Pho", "Chatuchak Market", "Khao San Road", "Chao Phraya River"],
    bestTime: "November to February (cool dry season)",
    food: ["Pad Thai", "Tom Yum Soup", "Green Curry", "Mango Sticky Rice", "Som Tum"],
    tips: ["Use BTS Skytrain to avoid traffic", "Dress modestly at temples", "Tuk-tuks are fun but negotiate price first", "Try street food — it's incredible"],
    budget: { accommodation: 35, food: 12, transport: 10, activities: 25 },
    weather: "Bangkok",
    trending: false,
  },
  {
    id: 18,
    name: "Rome, Italy",
    country: "Italy",
    region: "Europe",
    category: "Culture",
    rating: 4.8,
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1200&q=80",
    description: "Rome is an open-air museum where every cobblestone has a story. The Colosseum, Vatican City, Trevi Fountain — the Eternal City packs more history, art, and culinary brilliance into one place than anywhere on Earth.",
    attractions: ["Colosseum", "Vatican Museums & Sistine Chapel", "Trevi Fountain", "Roman Forum", "Pantheon"],
    bestTime: "April to June, September to October",
    food: ["Cacio e Pepe", "Carbonara", "Supplì", "Gelato", "Trapizzino"],
    tips: ["Book Vatican tickets weeks in advance", "Validate train tickets before boarding", "Beware of tourist traps near attractions", "Many fountains have drinkable water"],
    budget: { accommodation: 110, food: 45, transport: 20, activities: 45 },
    weather: "Rome",
    trending: false,
  },
  {
    id: 19,
    name: "Amsterdam, Netherlands",
    country: "Netherlands",
    region: "Europe",
    category: "City",
    rating: 4.6,
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=600&q=80",
    heroImage: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?w=1200&q=80",
    description: "Amsterdam is a city of canals, bicycles, world-class museums, and liberal culture. Its 17th-century canal ring, the Anne Frank House, Van Gogh Museum, and vibrant nightlife make it endlessly captivating.",
    attractions: ["Rijksmuseum", "Anne Frank House", "Van Gogh Museum", "Canal Ring", "Vondelpark"],
    bestTime: "April to May (tulips) / June to August (summer)",
    food: ["Stroopwafels", "Herring", "Bitterballen", "Dutch Pancakes", "Gouda Cheese"],
    tips: ["Rent a bicycle — it's the best way to explore", "Book museum tickets in advance", "Watch out for cyclists when walking", "I Amsterdam card for discounts"],
    budget: { accommodation: 120, food: 45, transport: 15, activities: 50 },
    weather: "Amsterdam",
    trending: false,
  },
];

// HERO SLIDE BACKGROUNDS
const HERO_SLIDES = [
  { url: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=1400&q=80", label: "Discover Beaches" },
  { url: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1400&q=80", label: "Explore Cities" },
  { url: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=1400&q=80", label: "Adventure Mountains" },
  { url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1400&q=80", label: "Tropical Escapes" },
];

// ITINERARY TEMPLATES
const ITINERARY_DATA = {
  "Bali, Indonesia": [
    { title: "Arrival & Beach Relaxation", desc: "Land at Ngurah Rai Airport, check-in to your villa, and head to Kuta or Seminyak Beach for a sunset welcome.", img: "https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8?w=200&q=70" },
    { title: "Ubud Tour", desc: "Explore Ubud — visit the Sacred Monkey Forest, walk Tegallalang Rice Terraces, and browse the Ubud Art Market.", img: "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=200&q=70" },
    { title: "Temple Hopping", desc: "Visit Tirta Empul, Tanah Lot sea temple at sunset, and explore Besakih Mother Temple.", img: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=200&q=70" },
    { title: "Nusa Penida Island", desc: "Day trip to Nusa Penida — see the iconic T-Rex cliff at Kelingking Beach and swim in Crystal Bay.", img: "https://images.unsplash.com/photo-1544550582-5c0dd7d3d56c?w=200&q=70" },
    { title: "Water Sports & Spa", desc: "Morning white-water rafting on the Ayung River, then an afternoon Balinese spa treatment.", img: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=200&q=70" },
    { title: "Shopping & Departure", desc: "Morning shopping at Seminyak boutiques and Sukawati Art Market for souvenirs.", img: "https://images.unsplash.com/photo-1555951015-6da893807703?w=200&q=70" },
    { title: "Free Exploration", desc: "Visit a cooking class, explore Canggu surf culture, or simply relax by the pool.", img: "https://images.unsplash.com/photo-1604999333679-b86d54738315?w=200&q=70" },
  ],
  "Paris, France": [
    { title: "Iconic Paris", desc: "Start at the Eiffel Tower, walk along Champs-Élysées to the Arc de Triomphe, and end with a Seine River cruise.", img: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=200&q=70" },
    { title: "Museums & Culture", desc: "Full morning at the Louvre. Afternoon at Musée d'Orsay for Impressionist art. Evening jazz in Saint-Germain.", img: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=200&q=70" },
    { title: "Montmartre & Sacré-Cœur", desc: "Morning in bohemian Montmartre, visit Sacré-Cœur basilica, watch street artists at Place du Tertre.", img: "https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=200&q=70" },
    { title: "Versailles Day Trip", desc: "Train to Versailles Palace — explore the Hall of Mirrors, royal apartments, and magnificent gardens.", img: "https://images.unsplash.com/photo-1519922639192-e73293ca430e?w=200&q=70" },
    { title: "Le Marais & Gastronomy", desc: "Explore Le Marais district, visit Place des Vosges, browse galleries. Book a French cooking class.", img: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=200&q=70" },
  ],
  "Tokyo, Japan": [
    { title: "Shinjuku & Arrival", desc: "Check in and explore Shinjuku — Tokyo Metropolitan Government Building observation deck (free!), Golden Gai.", img: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=200&q=70" },
    { title: "Asakusa & Traditional Tokyo", desc: "Senso-ji Temple at dawn before crowds, Nakamise shopping street, Tokyo Skytree for aerial views.", img: "https://images.unsplash.com/photo-1478436127897-769e1b3f0f36?w=200&q=70" },
    { title: "Harajuku & Shibuya", desc: "Meiji Shrine morning walk, Takeshita Street fashion, and the world-famous Shibuya crossing at night.", img: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=200&q=70" },
    { title: "Akihabara & Tech Culture", desc: "Explore Electric Town for anime, manga, and gadgets. Visit Akihabara arcades.", img: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=200&q=70" },
    { title: "Day Trip to Nikko", desc: "Scenic train to Nikko — elaborate UNESCO Toshogu Shrine, Kegon Waterfall, and Lake Chuzenji.", img: "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=200&q=70" },
  ],
  "Hyderabad, India": [
    { title: "Arrival & Old City Explore", desc: "Check in and head straight to Charminar for iconic photos, then explore Laad Bazaar for bangles and pearls.", img: "https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=200&q=70" },
    { title: "Golconda Fort & Sound Show", desc: "Morning at Golconda Fort — don't miss the acoustic clapping demonstration. Evening sound and light show.", img: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=200&q=70" },
    { title: "Hussain Sagar & HITEC City", desc: "Morning boat ride to Buddha statue at Hussain Sagar Lake. Afternoon explore Hyderabad's IT corridor.", img: "https://images.unsplash.com/photo-1605640840605-14ac1855827b?w=200&q=70" },
    { title: "Ramoji Film City", desc: "Full day at Asia's largest film city — studio tours, live shows, theme park rides, and behind-the-scenes experiences.", img: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=200&q=70" },
    { title: "Salar Jung Museum & Biryani Trail", desc: "Morning at Salar Jung Museum (world's largest one-man collection). Afternoon dedicated biryani trail!", img: "https://images.unsplash.com/photo-1588416936097-41850ab3d86d?w=200&q=70" },
  ],
  "Kerala, India": [
    { title: "Arrival in Kochi", desc: "Explore Fort Kochi — Chinese fishing nets, colonial churches, Jew Town spice market, and Kathakali dance show.", img: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=200&q=70" },
    { title: "Alleppey Houseboat", desc: "Board a traditional Kerala houseboat in Alleppey. Cruise through emerald backwaters, watch village life go by.", img: "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?w=200&q=70" },
    { title: "Munnar Tea Gardens", desc: "Drive through misty hills to Munnar — endless tea plantations, Eravikulam National Park, and fresh mountain air.", img: "https://images.unsplash.com/photo-1580889240889-7c64c6e00804?w=200&q=70" },
    { title: "Periyar Wildlife Sanctuary", desc: "Boat safari on Periyar Lake spotting elephants, bison, and deer. Spice plantation tour in Thekkady.", img: "https://images.unsplash.com/photo-1564659907532-6b5f98c8e70f?w=200&q=70" },
    { title: "Kovalam Beach & Ayurveda", desc: "Relax at Kovalam's crescent beach. Book an authentic Ayurvedic massage at a local wellness centre.", img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=200&q=70" },
  ],
  "Goa, India": [
    { title: "North Goa Beaches", desc: "Explore Baga, Calangute, and Anjuna beaches. Sunset at Vagator with views of Chapora Fort.", img: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=200&q=70" },
    { title: "Heritage & Churches", desc: "Visit Old Goa's UNESCO Basilica of Bom Jesus, Se Cathedral, and the Portuguese quarter of Fontainhas.", img: "https://images.unsplash.com/photo-1582972236019-ea4af5ffe587?w=200&q=70" },
    { title: "Dudhsagar Waterfalls", desc: "Full-day jeep safari through Bhagwan Mahavir Wildlife Sanctuary to the majestic Dudhsagar waterfalls.", img: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=200&q=70" },
    { title: "South Goa Serenity", desc: "Peaceful Palolem and Agonda beaches in South Goa — perfect for relaxation away from the crowds.", img: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?w=200&q=70" },
    { title: "Spice Plantation & Departure", desc: "Morning spice plantation tour with traditional Goan lunch. Evening departure.", img: "https://images.unsplash.com/photo-1601000938259-5a5e8e8e8c07?w=200&q=70" },
  ],
  "default": [
    { title: "Arrival & Check-in", desc: "Arrive at your destination, settle into your accommodation, explore the local neighborhood, and enjoy a welcome dinner.", img: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=200&q=70" },
    { title: "Major Attractions", desc: "Full day exploring the top sights and landmarks. A mix of cultural, historical, and natural highlights.", img: "https://images.unsplash.com/photo-1500835556837-99ac94a94552?w=200&q=70" },
    { title: "Local Culture & Food", desc: "Dive into local markets, street food, and cultural experiences. Join a cooking class or food tour.", img: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=200&q=70" },
    { title: "Nature & Adventure", desc: "Outdoor activities, scenic landscapes, hiking, or water sports depending on the destination's geography.", img: "https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=200&q=70" },
    { title: "Hidden Gems", desc: "Off the beaten path — explore local neighborhoods, lesser-known spots, and connect with locals.", img: "https://images.unsplash.com/photo-1519922639192-e73293ca430e?w=200&q=70" },
    { title: "Shopping & Souvenirs", desc: "Last-day shopping for local crafts, souvenirs, and gifts. Visit local markets and specialty shops.", img: "https://images.unsplash.com/photo-1555951015-6da893807703?w=200&q=70" },
    { title: "Relaxation & Departure", desc: "Final morning at leisure — a quiet breakfast, last-minute sights near the hotel, then transfer to departure.", img: "https://images.unsplash.com/photo-1506929562872-bb421503ef21?w=200&q=70" },
  ],
};

// BUDGET MULTIPLIERS
const BUDGET_RATES = {
  "Bali, Indonesia":      { Budget: [25,15,10,15],  Medium: [60,30,20,35],   Luxury: [200,80,50,100]  },
  "Paris, France":        { Budget: [80,40,20,25],  Medium: [140,65,35,55],  Luxury: [350,150,60,120] },
  "Tokyo, Japan":         { Budget: [60,30,15,25],  Medium: [110,50,25,50],  Luxury: [300,130,50,100] },
  "Switzerland":          { Budget: [120,50,40,40], Medium: [190,80,60,90],  Luxury: [450,180,100,180]},
  "Maldives":             { Budget: [250,60,80,70], Medium: [420,100,120,120],Luxury: [1200,300,200,250]},
  "Santorini, Greece":    { Budget: [100,40,20,30], Medium: [210,70,35,60],  Luxury: [500,160,70,140] },
  "New York, USA":        { Budget: [130,50,20,30], Medium: [220,90,35,70],  Luxury: [600,200,70,150] },
  "Dubai, UAE":           { Budget: [90,35,20,50],  Medium: [170,65,35,90],  Luxury: [500,160,70,200] },
  "Hyderabad, India":     { Budget: [15,8,6,10],    Medium: [35,15,12,20],   Luxury: [100,40,25,50]   },
  "Kerala, India":        { Budget: [20,10,8,15],   Medium: [45,18,15,25],   Luxury: [120,50,30,60]   },
  "Goa, India":           { Budget: [20,10,8,12],   Medium: [45,20,12,22],   Luxury: [130,55,25,55]   },
  "Manali, India":        { Budget: [15,8,10,15],   Medium: [35,15,15,25],   Luxury: [90,35,25,50]    },
  "Rajasthan, India":     { Budget: [20,10,10,12],  Medium: [45,20,18,22],   Luxury: [120,50,30,55]   },
  "Agra, India":          { Budget: [15,8,8,10],    Medium: [35,15,12,18],   Luxury: [90,35,20,45]    },
  "London, UK":           { Budget: [100,50,30,30], Medium: [160,70,40,60],  Luxury: [400,160,70,130] },
  "Singapore":            { Budget: [80,30,15,35],  Medium: [130,50,25,65],  Luxury: [350,120,40,130] },
  "Bangkok, Thailand":    { Budget: [20,10,8,15],   Medium: [50,20,15,30],   Luxury: [150,60,25,70]   },
  "Rome, Italy":          { Budget: [80,35,18,25],  Medium: [130,55,28,50],  Luxury: [350,140,50,110] },
  "Amsterdam, Netherlands":{ Budget: [90,40,15,30], Medium: [140,60,25,55],  Luxury: [380,140,40,110] },
  "default":              { Budget: [70,30,15,20],  Medium: [130,55,30,50],  Luxury: [400,150,80,120] },
};

// TRAVEL GUIDE ARTICLES
const GUIDE_ARTICLES = [
  { tag: "Tips", title: "10 Tips for a Budget-Friendly Trip", desc: "Explore the world without breaking the bank. Smart strategies for savvy travelers.", img: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400&q=70" },
  { tag: "Guides", title: "Complete Europe Travel Guide", desc: "Everything you need to know before visiting Europe — visas, transport, and must-sees.", img: "https://images.unsplash.com/photo-1471874708222-b77c76b7b8b4?w=400&q=70" },
  { tag: "Packing", title: "What to Pack for a Beach Vacation", desc: "A comprehensive checklist for your perfect beach holiday — nothing left behind.", img: "https://images.unsplash.com/photo-1526772662000-3f88f10405ff?w=400&q=70" },
  { tag: "Safety", title: "Travel Safety Tips Around the World", desc: "Stay safe and prepared. Essential security advice for solo and group travelers.", img: "https://images.unsplash.com/photo-1530268729831-4b0b9e170218?w=400&q=70" },
  { tag: "Culture", title: "Understanding Local Cultures", desc: "Respect local traditions and customs wherever you go. A traveler's guide to cultural etiquette.", img: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&q=70" },
  { tag: "Tips", title: "How to Find Cheap Flights", desc: "Expert tricks to score the best airfare deals — timing, tools, and tactics that work.", img: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=400&q=70" },
  { tag: "Guides", title: "India Travel Guide for First Timers", desc: "First time in India? This comprehensive guide covers everything from visas to customs.", img: "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400&q=70" },
  { tag: "Packing", title: "Minimalist Packing: The One-Bag Method", desc: "Travel the world with just one carry-on. How minimalist packing transforms your trips.", img: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=70" },
  { tag: "Safety", title: "Travel Insurance: Do You Really Need It?", desc: "An honest breakdown of travel insurance — when it's essential and when you can skip it.", img: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=400&q=70" },
];

// WEATHER ICON MAPPING
function getWeatherIcon(code) {
  if (code >= 200 && code < 300) return '⛈️';
  if (code >= 300 && code < 400) return '🌦️';
  if (code >= 500 && code < 600) return '🌧️';
  if (code >= 600 && code < 700) return '❄️';
  if (code >= 700 && code < 800) return '🌫️';
  if (code === 800) return '☀️';
  if (code === 801) return '🌤️';
  if (code === 802) return '⛅';
  if (code >= 803) return '☁️';
  return '🌡️';
}

// DAYS OF WEEK
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];